export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const LOAD_MORE_USERS = 'LOAD_MORE_USERS';
export const LOAD_MORE_USERS_REQUEST = 'LOAD_MORE_USERS_REQUEST';
export const NO_MORE_USERS = 'NO_MORE_USERS';